empower.url=http://localhost:8080/empower
empower.username=administrator
empower.password=


# localhost
otds.url=http://localhost:9999/otdsws/login
otds.client_id=Empower
otds.client_secret=
otds.scope=resource:Empower


otds.apiUrl=http://localhost:9999/otdsws/rest/authentication/credentials
otds.apiUserName=otadmin@otds.admin
otds.parola=

cs.url=https://d26apvl00188.test.local:2723/v1/communications?name=export_service_fulfillment&version=1


# remote
#otds.url=https://89.187.142.29:9999/otdsws/login
#otds.client_id=Empower
#otds.client_secret=C92hz42Ydh1liqp29OqWS4zSNpSH89Iu
#otds.scope=resource:Empower



